Repository Uspacy/uspacy-js-sdk, pull requests merged in 2023-12, with the labels that each got.

#42 [1617] change bank requisite interface
  package.json
  src/models/requisites.ts
Labels: size/s

#43 [2070] feature: email development next
  package.json
  src/models/email.ts
  src/services/EmailService/connect-email-box.dto.ts
  src/services/EmailService/index.ts
Labels: size/l

#44 [1789] update IChat interface
  package.json
  src/models/messenger.ts
Labels: size/xs

#45 [2070] feature: update routes for email
  package.json
  src/models/errors.ts
  src/services/EmailService/index.ts
Labels: size/s

#46 [2040] - feature. leads funnel
  package.json
  src/index.ts
  src/services/CrmLeadsFunnelsService/index.ts
Labels: size/s

#47 [2070] feature: add new routes for email
  package.json
  src/models/email.ts
  src/services/EmailService/index.ts
Labels: size/m

#48 [2070] feature: add filter params for email
  package.json
  src/models/email.ts
  src/services/EmailService/index.ts
Labels: size/s

#49 [2070] feature: add openCalendar type for email filters
  package.json
  src/models/email.ts
Labels: size/xs

#51 feature: up v
  package.json
Labels: size/xs

#52 [2070] feature: add mass deletion for letters
  package.json
  src/models/email.ts
  src/services/EmailService/create-email.dto.ts
  src/services/EmailService/index.ts
Labels: size/m

#53 [2070] feature: update types for email letters
  package.json
  src/models/email.ts
  src/services/EmailService/create-email.dto.ts
  src/services/EmailService/index.ts
Labels: size/m

#54 [2070] feature: update types for email
  package.json
  src/models/email.ts
  src/services/EmailService/create-email.dto.ts
Labels: size/s
