Repository Uspacy/uspacy-js-sdk, pull requests merged in 2023-10, with the labels that each got.

#5 feature: Adding mass completion
  package.json
  src/models/tasks.ts
  src/services/TasksService/dto/mass-actions.dto.ts
  src/services/TasksService/dto/mass-deletion.dto.ts
  src/services/TasksService/index.ts
Labels: size/m

#7 feature: adding mass editing
  package.json
  src/services/TasksService/dto/mass-actions.dto.ts
  src/services/TasksService/index.ts
Labels: size/m

#8 feature: adding tasks fields
  package.json
  src/models/field.ts
  src/services/TasksService/index.ts
Labels: size/l

#9 feature: adding admin checks
  package.json
  src/services/TasksService/dto/mass-actions.dto.ts
Labels: size/xs

#10 fix: Fix adding payload
  package.json
  src/services/TasksService/index.ts
Labels: size/xs

#11 [1690] feature: implement company
  package.json
  src/models/groups.ts
  src/services/GroupsService/dto/create-update-groups.dto.ts
  src/services/GroupsService/index.ts
  src/services/RolesService/create-update-role-dto.ts
  src/services/RolesService/index.ts
Labels: size/l

#12 [1690] fix: getGroups and add types
  package.json
  src/models/response.ts
  src/services/GroupsService/index.ts
Labels: size/s, size/xs

#13 [1690] fix: getGroups method
  src/services/GroupsService/index.ts
Labels: size/xs

#14 up version
  package.json
Labels: size/xs

#15 [1690] feature: newsfeed service
  package.json
  src/index.ts
  src/models/comment.ts
  src/models/newsfeed.ts
  src/services/CommentsService/index.ts
  src/services/NewsFeedService/NewsFeedService.ts
  src/services/NewsFeedService/dto/cteate-update-posts.dto.ts
  src/services/NewsFeedService/index.ts
Labels: size/l

#16 [1841] fix: updating payments
  package.json
  src/services/AuthService/dto/subscription.dto.ts
Labels: size/xs

#18 fix for getposts method
  package.json
  src/services/NewsFeedService/index.ts
Labels: size/xs

#19 [1690] bugfix: fix files
  package.json
  src/services/NewsFeedService/index.ts
Labels: size/s

#20 fix update method
  package.json
  src/services/NewsFeedService/dto/cteate-update-posts.dto.ts
  src/services/NewsFeedService/index.ts
  tsconfig.json
Labels: size/m

#21 [1690] hotfix: fix getposts for newsfeed
  package.json
  src/services/NewsFeedService/index.ts
Labels: size/xs

#22 [1690] bugfix: fix search
  package.json
  src/services/GroupsService/index.ts
Labels: size/xs

#17 [1845] feature: implement migartions
  package.json
  src/index.ts
  src/models/migrations.ts
  src/services/MigrationsService/dto/get-import-migrations-entities.dto.ts
  src/services/MigrationsService/index.ts
  tsconfig.declarations.json
  tsconfig.json
  yarn.lock
Labels: size/l

#1 Applications service
  package.json
  src/index.ts
  src/models/app.ts
  src/models/response.ts
  src/services/AppsService/dto/create-app.dto.ts
  src/services/AppsService/index.ts
  src/services/CommentsService/index.ts
  src/services/DepartmentsService/index.ts
  src/services/FilesService/index.ts
  src/services/GroupsService/index.ts
  src/services/NewsFeedService/index.ts
  src/services/TasksService/index.ts
  src/services/TasksStagesService/index.ts
  src/services/UsersService/index.ts
Labels: size/l

#23 [1698] feature: saved and simple filters
  package.json
  src/models/filters-presets.ts
  src/models/tasks.ts
Labels: size/m

#24 [1698] feature: add sort type to filter fields
  package.json
  src/models/filters-presets.ts
Labels: size/xs

#25 bugfix: get app by id method
  package.json
  src/services/AppsService/index.ts
Labels: size/xs

#27 [1698] feature: update types for new fields
  package.json
  src/models/tasks.ts
Labels: size/m

#28 [1827] feature: add meta to method
  package.json
  src/services/WebhooksService/index.ts
Labels: size/s

#26 [1906] move messenger and external messenger and external messenger into gen…
  package.json
  src/index.ts
  src/models/messenger.ts
  src/services/LeadsService/dto/create-lead.dto.ts
  src/services/MessengerService/index.ts
Labels: size/l
