Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-05, with the labels that each got.

#79 [2045] feature: delegation of tasks sdk
  package.json
  src/models/tasks.ts
  src/services/TasksService/dto/create-update-task.dto.ts
  src/services/TasksService/index.ts
Labels: size/s

#77 [1719] feature: hierarchies development sdk
  package.json
  src/models/tasks.ts
  src/services/TasksService/index.ts
  src/services/TasksStagesService/index.ts
Labels: size/m

#82 Update publish-alpha.yml
  .github/workflows/publish-alpha.yml
Labels: size/xs

#80 [3122] feat: monday migration
  package.json
  src/models/migrations.ts
  src/services/MigrationsService/dto/get-import-migrations-entities.dto.ts
  src/services/MigrationsService/index.ts
Labels: size/m

#81 [1751] update message interface for meta
  package.json
  src/models/messenger.ts
Labels: size/s
