Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-11, with the labels that each got.

#110 [4006] feat: improve logic for new store
  package.json
  src/models/crm-entities.ts
  src/models/crm-filter-field.ts
  src/models/crm-mass-actions.ts
  src/services/CrmEntitiesService/index.ts
  src/services/CrmProductsService/index.ts
  src/services/CrmTasksService/index.ts
Labels: size/l

#112 [4306] feat: add optional key history
  package.json
  src/models/history.ts
Labels: size/xs

#116 [4487] feat: incoming webhooks
  package.json
  src/models/webhooks.ts
  src/services/WebhooksService/dto/create-webhook.dto.ts
  src/services/WebhooksService/index.ts
Labels: size/m

#119 fix: fixing selector for couchdb
  package.json
  src/services/CouchdbService/index.ts
Labels: size/xs
