Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-12, with the labels that each got.

#120 [4162] feat: analytics constructor
  package.json
  src/index.ts
  src/models/analytics.ts
  src/services/AnalyticsService/index.ts
Labels: size/l

#122 [4162] feat add tariff
  package.json
  src/models/analytics.ts
  src/models/response.ts
  src/services/AnalyticsService/index.ts
Labels: size/s

#123 [4434] feat: change interface
  package.json
  src/models/announcers.ts
  src/services/AnnouncersService/dto/announcers-dto.ts
Labels: size/s

#124 [4540] feature: email signatures development
  package.json
  src/models/email.ts
  src/services/EmailService/create-email.dto.ts
  src/services/EmailService/index.ts
  src/services/EmailService/signature.dto.ts
Labels: size/m

#126 [4434] feat: return interfaces
  package.json
  src/models/announcers.ts
  src/services/AnnouncersService/dto/announcers-dto.ts
Labels: size/s

#128 [4540] feature: signatures tarrifs restrictions
  package.json
  src/models/email.ts
  src/services/EmailService/index.ts
Labels: size/xs

#127 [4434] feat: change interface
  package.json
  src/models/announcers.ts
  src/services/AnnouncersService/dto/announcers-dto.ts
Labels: size/s
