Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-10, with the labels that each got.

#105 [4155] feature: add smtp fields for email
  package.json
  src/models/email.ts
  src/services/EmailService/connect-email-box.dto.ts
Labels: size/xs

#107 [3402] feature: couchdb service/update service for new couchdb backend
  package.json
  src/demo/index.ts
  src/models/tasks-settings.ts
  src/services/CouchdbService/index.ts
  src/services/TasksService/index.ts
Labels: size/m

#108 [3402] feature: update docs search
  package.json
  src/services/CouchdbService/index.ts
  src/services/TasksService/index.ts
Labels: size/s

#89 [3402] feat: couch db service for store common user data
  package.json
  src/demo/index.ts
  src/models/couchdb.ts
  src/models/filter-preset.ts
  src/models/tasks-settings.ts
  src/services/CouchdbService/index.ts
  src/services/TasksService/dto/create-task-table-settings.dto.ts
  src/services/TasksService/index.ts
Labels: size/l

#100 [2790] feat: add history service
  package.json
  src/index.ts
  src/models/history.ts
  src/services/HistoryService/index.ts
Labels: size/m
