Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-03, with the labels that each got.

#68 [2406] update IMessage
  package.json
  src/models/messenger.ts
Labels: size/xs

#64 [2070] feature: email development sdk
  package.json
  src/models/email.ts
  src/services/EmailService/connect-email-box.dto.ts
  src/services/EmailService/create-email.dto.ts
  src/services/EmailService/index.ts
Labels: size/l, size/m, size/s

#71 [2493] - feature. crm store
  package.json
  src/index.ts
  src/models/crm-calls.ts
  src/models/crm-card-blocks.ts
  src/models/crm-document-template.ts
  src/models/crm-entities.ts
  src/models/crm-errors.ts
  src/models/crm-filter-field.ts
  src/models/crm-filters.ts
  src/models/crm-funnel.ts
  src/models/crm-kanban.ts
  src/models/crm-mass-actions.ts
  src/models/crm-products-category.ts
  src/models/crm-products-for-entity.ts
  src/models/crm-products-taxes.ts
  src/models/crm-products-unit.ts
  src/models/crm-products.ts
  src/models/crm-requisite.ts
  src/models/crm-stages.ts
  src/models/crm-tasks.ts
  src/models/field.ts
  src/services/CrmCallsService/index.ts
  src/services/CrmCompaniesService/index.ts
  src/services/CrmContactsService/index.ts
  src/services/CrmDealsFunnelsService/index.ts
  src/services/CrmDealsService/index.ts
  src/services/CrmDealsStagesService/index.ts
  src/services/CrmDocumentTemplatesService/index.ts
  src/services/CrmEntitiesService/index.ts
  src/services/CrmLeadsFunnelsService/index.ts
  src/services/CrmLeadsService/index.ts
  src/services/CrmLeadsStagesService/index.ts
  src/services/CrmProductsCategoryService/index.ts
  src/services/CrmProductsForEntityService/index.ts
  src/services/CrmProductsService/index.ts
  src/services/CrmProductsTaxesService/index.ts
  src/services/CrmProductsUnitService/index.ts
  src/services/CrmRequisitesService/dto/requisite-params.dto.ts
  src/services/CrmRequisitesService/index.ts
  src/services/CrmTasksService/index.ts
Labels: size/XXL

#73 [2968] crm products fix namespace
  package.json
  src/services/CrmProductsForEntityService/index.ts
Labels: size/xs
