Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-02, with the labels that each got.

#60 [2520] feature: add field for response interface
  package.json
  src/models/response.ts
Labels: size/xs

#62 [2520] feature: up v
  package.json
Labels: size/xs

#61 [2355] feature: new major update for templates
  package.json
  src/models/tasks.ts
  src/services/TasksService/dto/create-update-task.dto.ts
  src/services/TasksService/index.ts
Labels: size/l

#56 [1734] widget integration
  package.json
  src/models/messenger.ts
  src/services/LeadsService/dto/create-lead.dto.ts
  src/services/MessengerService/index.ts
Labels: size/m, size/s

#65 [2371] feature: add notifications interface
  package.json
  src/models/notifications.ts
Labels: size/s

#63 [2494] graftf develop
  package.json
  src/models/messenger.ts
Labels: size/xs
