Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-07, with the labels that each got.

#76 [2991] settings integration
  package.json
  src/models/crm-entities.ts
  src/models/email.ts
  src/services/EmailService/connect-email-box.dto.ts
  src/services/EmailService/create-email.dto.ts
  src/services/EmailService/index.ts
  src/services/LeadsService/dto/create-lead.dto.ts
Labels: size/l, size/m, size/s

#85 [3358] feature: add vertical sorting for tasks table/sdk
  package.json
  src/models/tasks.ts
Labels: size/xs

#70 [2186] feat: add automations
  package.json
  src/index.ts
  src/models/automations.ts
  src/services/AutomationsService/index.ts
Labels: size/m

#90 [2040] feat: add portal id to automation interface
  package.json
  src/models/automations.ts
Labels: size/xs

#92 [3402] feature: couchdb service/task table settings
  package.json
  src/models/task-settings.ts
  src/services/TasksService/dto/create-task-table-settings.dto.ts
  src/services/TasksService/index.ts
Labels: size/m, size/s

#93 [3402] feature: couchdb_service/add sorting model
  package.json
  src/models/task-settings.ts
Labels: size/xs

#88 [2993] update messages type
  package.json
  src/models/messenger.ts
Labels: size/xs

#95 [3402] feature: couchdb service/filters presets
  src/demo/index.ts
  src/models/couchdb.ts
  src/models/filter-preset.ts
  src/services/CouchdbService/index.ts
  src/services/TasksService/index.ts
Labels: size/m, size/s

#96 [3402] feature: couchdb service/bulk docs method for mass update items
  package.json
  src/demo/index.ts
  src/services/CouchdbService/index.ts
  src/services/TasksService/index.ts
Labels: size/s
