Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-06, with the labels that each got.

#83 [3007] feat: change groups interface
  package.json
  src/models/groups.ts
  src/services/GroupsService/dto/create-update-groups.dto.ts
  src/services/GroupsService/index.ts
Labels: size/m, size/s

#84 [3329] feat: change activity for new routes
  package.json
  src/models/crm-tasks.ts
Labels: size/s

#86 [3326] feature: update logic for letter contact name sdk
  package.json
  src/models/email.ts
Labels: size/xs

#87 [3432] feature: OAuth microsoft integration/sdk
  package.json
  src/models/email.ts
  src/services/EmailService/index.ts
Labels: size/s
