Repository Uspacy/uspacy-js-sdk, pull requests merged in 2024-08, with the labels that each got.

#97 [3589] fix: up v
  package.json
Labels: size/xs

#98 [3366] feat: update root parent
  package.json
  src/models/notifications.ts
Labels: size/xs

#102 [feat] improve refresh token logic
  package.json
  src/core/HttpClient/index.ts
Labels: size/l

#91 [3393] feat: activity filters
  package.json
  src/services/CrmTasksService/index.ts
Labels: size/s
