Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-05, with the labels that each got.

#131 [4742] feature: add new coupons
  package.json
  src/models/tariffs.ts
  src/services/AuthService/dto/subscription.dto.ts
  src/services/AuthService/index.ts
Labels: size/m, size/s

#162 [feat] bump axios to 1.9.0
  package.json
  yarn.lock
Labels: size/s

#157 [5137] feature: transfer of cases
  package.json
  src/models/transferOfCases.ts
  src/services/CrmEntitiesService/index.ts
  src/services/CrmTasksService/index.ts
  src/services/GroupsService/index.ts
  src/services/TasksService/index.ts
Labels: size/l

#161 [5742] feat: update iformother
  package.json
  src/models/forms.ts
Labels: size/xs

#166 [5793] feat: add call duration type
  package.json
  src/models/field.ts
Labels: size/xs
