Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-07, with the labels that each got.

#173 [2321] feat: change body for mass edit activity
  package.json
  src/services/CrmTasksService/index.ts
Labels: size/xs

#168 [5735] feat: add IFormAfter
  package.json
  src/models/forms.ts
Labels: size/s, size/xs

#165 [5376] feature: email templates
  package.json
  src/index.ts
  src/models/email-template-filter.ts
  src/models/email-template.ts
  src/services/MarketingService/index.ts
Labels: size/l, size/m

#169 [5735] feat: forms settings design tab
  package.json
  src/models/forms.ts
Labels: size/m, size/s

#179 [4879] feature: updating tasks custom fields routes
  package.json
  src/services/TasksService/index.ts
Labels: size/s
