Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-02, with the labels that each got.

#139 [4852] feature: couchdb crm presets
  package.json
  src/models/couchdb.ts
  src/models/crm-filter-field.ts
  src/models/filter-preset.ts
  src/models/table-settings.ts
  src/services/PouchdbService/index.ts
Labels: size/m

#141 [4731] feat: dependent lists
  package.json
  src/models/dependencies-list.ts
  src/models/field.ts
  src/services/CrmEntitiesService/index.ts
Labels: size/m

#144 [4975] feature: new tasks kanban
  package.json
  src/models/response.ts
  src/models/tasks-stages.ts
  src/models/tasks.ts
  src/services/TasksService/index.ts
  src/services/TasksStagesService/index.ts
Labels: size/l

#146 [5188] feat analytic report change interface
  package.json
  src/models/analytics.ts
Labels: size/xs

#143 [5062] feature: zoom gmeeting integrations
  package.json
  src/models/calendars.ts
  src/models/oauthIntegrations.ts
  src/services/AuthService/dto/response-oauth-data.dto.ts
  src/services/AuthService/index.ts
  src/services/CrmTasksService/calendars-settings.dto.ts
  src/services/CrmTasksService/index.ts
Labels: size/l
