Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-01, with the labels that each got.

#129 [4742] feature: new billing
  package.json
  src/models/tariffs.ts
  src/services/AuthService/dto/subscription.dto.ts
  src/services/AuthService/index.ts
Labels: size/l

#130 [4522] feat: add fields announcers interface
  package.json
  src/models/announcers.ts
Labels: size/xs

#134 [Feat] change interface portal settings
  package.json
  src/models/settings.ts
Labels: size/xs

#135 [4789] feat: funnel permissions
  src/models/crm-funnel.ts
Labels: size/m, size/xs

#137 [4754] feat: required field
  package.json
  src/models/crm-funnel.ts
  src/models/field.ts
Labels: size/s

#136 [4452] feat: add announce popup
  package.json
  src/models/announcers.ts
  src/services/AnnouncersService/dto/announcers-dto.ts
Labels: size/m, size/s

#138 [4789] feat: funnel permissions
  package.json
  src/services/LeadsService/dto/create-lead.dto.ts
Labels: size/xs

#117 [4544] feat: permissions funnels
  package.json
  src/models/roles.ts
  src/services/RolesService/create-update-role-dto.ts
  src/services/RolesService/index.ts
Labels: size/m
