Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-04, with the labels that each got.

#125 [3229] feat: update fields types
  package.json
  src/helpers/index.ts
  src/index.ts
  src/models/field.ts
  src/models/forms.ts
  src/models/resources.ts
  src/services/ResourcesService/index.ts
Labels: size/l, size/xs

#155 [sentry][USPACY-1V1] add aborted for documents interface
  package.json
  src/models/crm-document-template.ts
Labels: size/xs

#159 [3396] feature: amount deals and smart objects
  package.json
  src/models/crm-entities.ts
  src/models/crm-filters.ts
  src/services/CrmEntitiesService/index.ts
Labels: size/m
