Repository Uspacy/uspacy-js-sdk, pull requests merged in 2025-08, with the labels that each got.

#154 [3980] feat: booking schedule
  package.json
  src/helpers/index.ts
  src/models/booking.ts
  src/models/forms.ts
  src/models/resources.ts
Labels: size/l, size/m

#181 [2030] feat: ai service
  package.json
  src/index.ts
  src/services/AIService/index.ts
Labels: size/m

#184 [6476] feat: add getCallTranscribe
  package.json
  src/services/AIService/index.ts
Labels: size/s, size/xs

#185 [6477] feat: call ai resume
  package.json
  src/services/AIService/index.ts
Labels: size/s

#186 [6089] feat: add mass activity reopen
  package.json
  src/services/CrmTasksService/index.ts
Labels: size/s
